### ISSUE TITLE
Fix redirect when Teller is not enabled.

### ISSUE THREAD

**Issue by Helghardt** [myfundo/wallet-ionic#1]
If a normal user goes to Teller and then click on any of the tabs, the user is redirected to the login page. 

It could work that the user can view all the Teller features, but not "Accept" any offers unless Teller mode is activated.

**Comment by OdinsPlasmaRifle** [comment]
I have updated the teller page to not show certain options when a the teller "permissions" are not enabled. The history option will show for all users. If the user enables the teller" permissions" the app will display the "New Transactions" and "Active Offers" menu options.
