### ISSUE TITLE
Do something if no Tellers are found.

### ISSUE THREAD

**Issue by Helghardt** [myfundo/wallet-ionic#3]
When the User creates a deposit, and waiting for Tellers to "Accept", then the offer should expire. We can hard code the Offer to 45 seconds.

It would be cool to add a count down clock.

Also, if a Teller has accepted, then the User can view the Teller on the map. However, we must continue searching for more Tellers in the background and update the map. The User should be able to view the different Teller's information before proceeding.

**Comment by OdinsPlasmaRifle** [comment]
A timeout of 60 seconds has been set for "offer" acceptance. However, I would recommend something more like 5 min, as I doubt there will be enough users (at least initially) to make a 60 second timeout viable.

The map of teller offers is also updated continuously with any additional offers that come in.
